#!/usr/bin/env bash
# Emdee — build a self-contained x86_64 AppImage.
# SPDX-License-Identifier: GPL-3.0-or-later
#
#   packaging/linux/build-appimage.sh            # -> dist/Emdee-<version>-x86_64.AppImage
#
# The bundle is a relocatable CPython from python-appimage (manylinux_2_28, so
# it runs on any glibc 2.28+ distribution) with the pinned requirements
# pip-installed into it. The PyQt6 wheels already carry Qt and Chromium, so
# nothing else is compiled or vendored by hand.
#
# Needs: curl, python3 (only to read the GitHub API answer), and a writable
# working directory. appimagetool is downloaded on the fly.

set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
WORK="${REPO_ROOT}/build/appimage"
DIST="${REPO_ROOT}/dist"
PYTHON_TAG="python3.11"
PLATFORM="manylinux_2_28_x86_64"

say() { printf '==> %s\n' "$*"; }

VERSION="$(cd "${REPO_ROOT}" && python3 -c 'import app; print(app.APP_VERSION)')"
OUTPUT="${DIST}/Emdee-${VERSION}-x86_64.AppImage"

rm -rf "${WORK}"
mkdir -p "${WORK}" "${DIST}"
cd "${WORK}"

# ------------------------------------------------------------- base python
say "locating the ${PYTHON_TAG} ${PLATFORM} base image"
PYTHON_URL="$(
    curl -fsSL "https://api.github.com/repos/niess/python-appimage/releases/tags/${PYTHON_TAG}" |
    python3 -c '
import json, sys
platform = sys.argv[1]
names = [
    (a["name"], a["browser_download_url"])
    for a in json.load(sys.stdin)["assets"]
    if a["name"].endswith(platform + ".AppImage")
]
print(sorted(names)[-1][1])
' "${PLATFORM}"
)"
say "downloading ${PYTHON_URL##*/}"
curl -fsSL -o python.AppImage "${PYTHON_URL}"
chmod +x python.AppImage
# --appimage-extract needs no FUSE, which CI runners and containers lack.
./python.AppImage --appimage-extract >/dev/null
mv squashfs-root AppDir

PY="AppDir/opt/${PYTHON_TAG}/bin/${PYTHON_TAG}"
[[ -x "${PY}" ]] || { echo "unexpected base image layout: ${PY} missing" >&2; exit 1; }

# ----------------------------------------------------------- dependencies
say "installing the pinned requirements"
"${PY}" -m pip install --no-cache-dir --no-warn-script-location --upgrade pip >/dev/null
"${PY}" -m pip install --no-cache-dir --no-warn-script-location -r "${REPO_ROOT}/requirements.txt"

# ------------------------------------------------------------- application
say "copying the application"
install -d AppDir/opt/emdee
cp -r "${REPO_ROOT}/app" AppDir/opt/emdee/
find AppDir/opt/emdee -name '__pycache__' -prune -exec rm -rf {} +
install -m644 "${REPO_ROOT}/WELCOME.md" "${REPO_ROOT}/LICENSE" "${REPO_ROOT}/NOTICE" AppDir/opt/emdee/

# The base image's own launcher, desktop entry and icon describe "Python";
# replace them with Emdee's.
rm -f AppDir/AppRun AppDir/*.desktop AppDir/*.png AppDir/*.svg AppDir/.DirIcon
rm -rf AppDir/usr/share/applications AppDir/usr/share/metainfo

cat > AppDir/AppRun <<EOF
#!/bin/sh
# Generated by packaging/linux/build-appimage.sh.
HERE="\$(dirname "\$(readlink -f "\$0")")"
export APPDIR="\${APPDIR:-\$HERE}"
# The base image is a relocatable CPython; these keep it from wandering into
# the host's Python installation.
unset PYTHONHOME
export PYTHONNOUSERSITE=1
export PYTHONPATH="\$APPDIR/opt/emdee"
export SSL_CERT_FILE="\${SSL_CERT_FILE:-\$APPDIR/opt/_internal/certs.pem}"
exec "\$APPDIR/opt/${PYTHON_TAG}/bin/${PYTHON_TAG}" -s -m app.main "\$@"
EOF
chmod 755 AppDir/AppRun

install -m644 "${REPO_ROOT}/packaging/emdee.desktop" AppDir/emdee.desktop
sed -i -e 's/^Exec=emdee/Exec=AppRun/' -e '/^TryExec=/d' AppDir/emdee.desktop
cp "${REPO_ROOT}/packaging/icons/hicolor/256x256/apps/emdee.png" AppDir/emdee.png
ln -s emdee.png AppDir/.DirIcon
for size_dir in "${REPO_ROOT}"/packaging/icons/hicolor/*/apps; do
    rel="${size_dir#"${REPO_ROOT}/packaging/icons/"}"
    install -d "AppDir/usr/share/icons/${rel}"
    cp "${size_dir}"/* "AppDir/usr/share/icons/${rel}/"
done

# ----------------------------------------------------------------- package
say "downloading appimagetool"
curl -fsSL -o appimagetool \
    "https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage"
chmod +x appimagetool

say "packing ${OUTPUT##*/}"
ARCH=x86_64 ./appimagetool --appimage-extract-and-run --no-appstream AppDir "${OUTPUT}"
chmod +x "${OUTPUT}"
say "done: ${OUTPUT} ($(du -h "${OUTPUT}" | cut -f1))"
