#!/usr/bin/env bash
# Emdee — install the desktop entry, the launcher and the icon theme.
# Copyright (C) 2026 Adrià Bonnin Catalán
# SPDX-License-Identifier: GPL-3.0-or-later
#
# Everything goes under $XDG_DATA_HOME and ~/.local/bin, so no root is needed
# and nothing outside the user's home directory is touched.

set -euo pipefail

APP_ID="emdee"
APP_NAME="Emdee"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SCRIPT_DIR}/.." && pwd)"

DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"
BIN_DIR="${HOME}/.local/bin"
DESKTOP_DIR="${DATA_HOME}/applications"
ICON_DIR="${DATA_HOME}/icons/hicolor"

say()  { printf '  %s\n' "$*"; }
warn() { printf '  ! %s\n' "$*" >&2; }
die()  { printf 'error: %s\n' "$*" >&2; exit 1; }

printf '\nInstalling %s from %s\n\n' "${APP_NAME}" "${REPO_ROOT}"

# --------------------------------------------------------------- interpreter
if [[ -x "${REPO_ROOT}/.venv/bin/python" ]]; then
    PYTHON="${REPO_ROOT}/.venv/bin/python"
    say "using the project virtualenv: ${PYTHON}"
elif command -v python3 >/dev/null 2>&1; then
    PYTHON="$(command -v python3)"
    say "using the system interpreter: ${PYTHON}"
else
    die "no Python 3 interpreter found"
fi

if ! "${PYTHON}" -c 'import PyQt6.QtWebEngineWidgets' >/dev/null 2>&1; then
    warn "PyQt6-WebEngine is not importable with ${PYTHON}."
    warn "Install it before launching (see the README), or create a venv:"
    warn "  python -m venv .venv && .venv/bin/pip install -r requirements.txt"
fi

# ------------------------------------------------------------------ icons
if [[ ! -d "${REPO_ROOT}/packaging/icons/hicolor" ]]; then
    say "generating icons"
    "${PYTHON}" "${REPO_ROOT}/tools/build_icons.py" >/dev/null \
        || die "could not generate the icons (see tools/build_icons.py)"
fi

installed_icons=0
while IFS= read -r -d '' source; do
    relative="${source#"${REPO_ROOT}/packaging/icons/hicolor/"}"
    target="${ICON_DIR}/${relative}"
    mkdir -p "$(dirname -- "${target}")"
    install -m 0644 "${source}" "${target}"
    installed_icons=$((installed_icons + 1))
done < <(find "${REPO_ROOT}/packaging/icons/hicolor" -type f \
             \( -name '*.png' -o -name '*.svg' \) -print0)
say "installed ${installed_icons} icon files into ${ICON_DIR}"

# --------------------------------------------------------------- launcher
mkdir -p "${BIN_DIR}"
LAUNCHER="${BIN_DIR}/${APP_ID}"
cat > "${LAUNCHER}" <<EOF
#!/bin/sh
# Generated by ${APP_ID}/packaging/install.sh — do not edit by hand.
exec env PYTHONPATH="${REPO_ROOT}\${PYTHONPATH:+:\$PYTHONPATH}" \\
    "${PYTHON}" -m app.main "\$@"
EOF
chmod 0755 "${LAUNCHER}"
say "installed launcher: ${LAUNCHER}"

case ":${PATH}:" in
    *":${BIN_DIR}:"*) ;;
    *) warn "${BIN_DIR} is not on your PATH; add it to run '${APP_ID}' from a shell" ;;
esac

# ------------------------------------------------------------ desktop entry
mkdir -p "${DESKTOP_DIR}"
DESKTOP_FILE="${DESKTOP_DIR}/${APP_ID}.desktop"
# The launcher may live outside PATH, so the entry gets its absolute location.
sed -e "s|^Exec=${APP_ID} %f\$|Exec=${LAUNCHER} %f|" \
    -e "s|^Exec=${APP_ID}\$|Exec=${LAUNCHER}|" \
    -e "s|^TryExec=${APP_ID}\$|TryExec=${LAUNCHER}|" \
    "${REPO_ROOT}/packaging/${APP_ID}.desktop" > "${DESKTOP_FILE}"
chmod 0644 "${DESKTOP_FILE}"
say "installed desktop entry: ${DESKTOP_FILE}"

if command -v desktop-file-validate >/dev/null 2>&1; then
    if desktop-file-validate "${DESKTOP_FILE}"; then
        say "desktop entry validates cleanly"
    else
        warn "desktop-file-validate reported problems (see above)"
    fi
fi

# ------------------------------------------------------------------ caches
if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database "${DESKTOP_DIR}" >/dev/null 2>&1 || true
    say "refreshed the desktop database"
fi

if command -v gtk-update-icon-cache >/dev/null 2>&1; then
    gtk-update-icon-cache --force --quiet "${ICON_DIR}" >/dev/null 2>&1 || true
    say "refreshed the icon cache"
fi

if command -v xdg-mime >/dev/null 2>&1; then
    xdg-mime default "${APP_ID}.desktop" text/markdown >/dev/null 2>&1 || true
    say "registered as a handler for text/markdown"
fi

printf '\nDone. Launch it from your application menu, or run: %s\n\n' "${APP_ID}"
